@startuml belajar

entity Pengguna {
  * IdPengguna VARCHAR(100) <<PK>>
  --
  * Nama VARCHAR(100) NOT NULL
  * Alamat TEXT
}

entity Kurir {
  * IdKurir VARCHAR(100) <<PK>>
  --
  * Nama VARCHAR(100)
}

Pengguna |

@enduml